name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      device:
        description: 'select version to build'
        default: '2.26'
        required: false

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  docker build --build-arg GLIBC_VERSION=${{ github.event.inputs.device }} -t  my-image-name:$(date +%s) .  
